media:
  - name: images
    label: Images
    input: content/assets/images
    output: /images
    categories: [ image ]
  - name: certs
    label: Certs
    input: content/assets/certs
    output: /certs
    categories: [ cert ]
content:
  - name: blogs
    label: Blogs
    type: collection
    path: content/blogs
    filename: '{primary}.md'
    view:
      fields: [ author, title, description, date, tags, showToc ]
    fields:
      - name: author
        label: Author
        type: string
        default: "Luqinthar Sudarsono"
    
      - name: title
        label: Title
        type: string
        default: ""
    
      - name: description
        label: Description
        type: string
        default: ""
    
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
    
      - name: tags
        label: Tags
        type: list   # Ubah menjadi list untuk array
        options:
          creatable: true
          multiple: true
          values: []
    
      - name: showToc
        label: Show Table of Contents
        type: boolean
        default: true

